{% set version = "0.6.2" %}

{% set native = 'm2w64-' if win else '' %}

package:
  name: ytop
  version: {{ version }}

source:
  url: https://github.com/cjbassi/ytop/archive/{{ version }}.tar.gz
  sha256: d9fd6ce00e27de894bc0790947fbeab40e81e34afa5ead5a53d126c458d50e99

build:
  number: 0
  # not compiling and not yet supported by upstream
  skip: true  # [win]
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - rust
    - {{ compiler('c') }}   # [unix]
    - {{ native }}binutils    # [win]

test:
  commands:
    - ytop --help

about:
  home: https://github.com/cjbassi/ytop
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A TUI system monitor written in Rust
  dev_url: https://github.com/cjbassi/ytop
  doc_url: https://github.com/cjbassi/ytop#Usage

extra:
  recipe-maintainers:
    - dbast
